### ISSUE TITLE
Bot refuses to use proxies

### ISSUE THREAD

**Issue by nautics889** [Topinambur223606/PixelPlanetTools#22] opened 2020-05-20 16:25 UTC
It looks like bot doesn't use proxy which i supply and just continue to work using my IP. 
I discovered that in such way:
1) Run bot providing proxy address and credentials
2) Everything is OK, connection is established and bot asks me to enter a captcha:
`[CAPTCHA]       Please go to browser and place pixel, then return and press any key `
3) I open a browser then set proxy settings and open PixelPlanet to resolve the captcha
4) After one is done i open terminal and press any key. Nothing happens as a result, bot is still asking for captha resolving
5) **THEN** i open a new, fresh browser with unset proxy settings and going to resolve captcha **with my IP**
6)  Once i press any key in the terminal bot resume work 

I saw you've committed changes to `WebSocketWrapper` and it now depends on `ProxySettings` as it has to be. Could you please check that again?

**Comment by Topinambur223606** [comment] 2020-09-20 13:17
I found out that websocket library ignores attempt to set proxy if address does not start with "http://".
Websocket logs contain message `'url' is an invalid URL`, but no exception is thrown, so this error was left unnoticed.
Since it's natural for user to ignore such prefix, I implemented adding it before passing address to websocket: 6bc90b435eb966245a862f2dcbbfb39ecdff37b9.
Please evaluate the fix and close the issue if bug is no longer reproducible.

**Comment by Topinambur223606** [comment] 2020-10-15 12:02
Hello @nautics889,
Is issue still relevant?

**Comment by Topinambur223606** [comment] 2020-10-20 19:02
I suggest that the issue was caused by silent proxy settings rejecting and is no longer relevant.
Please create a new one if it is still reproducible.

**Closed by Topinambur223606** 2020-10-20 19:02 UTC
Labels: bug

**Comment by nautics889** [comment] 2021-01-28 23:14
I'm really sorry for haven't responded for so long.
I've just checked the latest release with some free proxy, it looks like everything went well. At least bot recognized proxy and failed since it's a free one.
Nevermind, guess I would manage to test full flow this weekend.
Thank you a lot for resolving this issue, it was really crucial.
