### ISSUE TITLE
Assist being considered attack

### ISSUE THREAD

**Issue by Checkzin** [Topinambur223606/PixelPlanetTools#23] opened 2020-06-26 15:47 UTC
I've been building some images around the map, but tried to build one with a friend using the bot. We are using the same coordinates and image, but for some reason his pixels are considered attacks

**Comment by Colin-Mac-Donald** [comment] 2020-06-27 14:59
I'm not able to replicate this by running two instances with the same image and coordinates. They see each other creating the pixels, but the colour is correct and they go into the assist branch here rather than the attack.  This code looks robust enough.

if (desiredColor == e.Color)
{
    msgGroup = MessageGroup.Assist;
    builtInLastMinute++;
}
else
{
    msgGroup = MessageGroup.Attack;
    griefedInLastMinute++;
    gotGriefed?.Set();
}

Is there any more info that you can provide to help replicate this?

Are you both running the same version?  Is the image definitely the same on both machines?  Can you provide a copy of it?  Did you share the image file directly or paste it into some sharing program that might have modified it?  Any chance that one of you ran it through pixelplanet.fun/convert and the other didn't?

**Comment by Topinambur223606** [comment] 2020-09-20 13:27
Hello @Checkzin,
Please look at the comment above since it may be the cause.
If not and if issue is still reproducible, is it possible to retrieve logs and exact copies of both images you are using?
If the problem is no longer relevant or reproducible, please consider closing the issue.

**Comment by Topinambur223606** [comment] 2020-10-15 12:04
Hello @Checkzin,
Is the issue still relevant?

**Comment by Topinambur223606** [comment] 2020-10-20 19:01
I suggest that the issue is no longer relevant.
Please create a new one if it is reproducible.

**Closed by Topinambur223606** 2020-10-20 19:01 UTC
