### ISSUE TITLE
Endless reconnect since 2/8/21

### ISSUE THREAD

**Issue by JusSumBum** [Topinambur223606/PixelPlanetTools#31] opened 2021-02-09 23:56 UTC
Working one second, then not. Not working since then, or about 24 hours now.

with debug turned on:

17:54:30.161  [TECHSTATE]     Connecting via websocket...
17:54:30.318  [DEBUG]  T1   | Websocket log message: , Not a WebSocket handshake response.
17:54:30.319  [DEBUG]  T1   | WebSocket_OnClose(): start
17:54:30.319  [DEBUG]  T1   | WebSocket_OnClose(): invoking OnConnectionLost
17:54:30.319  [ERROR]         Websocket connection closed, trying to reconnect...

**Comment by Topinambur223606** [comment] 2021-02-14 12:45
I looked at [websocket implementation](https://github.com/sta/websocket-sharp) and found [following](https://github.com/sta/websocket-sharp/blob/69582c3095d7febc6ac5f8251897d8eb1f1c2885/websocket-sharp/HttpRequest.cs#L70):
`Headers["User-Agent"] = "websocket-sharp/1.0";`
With such header, initiating websocket connection fails with 403 Forbidden status code.
Both removing or replacing it with another value allows bot to work as intended. I would prefer replacing it with Chrome 87 user agent because requests with no user agent can be blacklisted as well.

Unfortunately, connecting with such user agent is library internal implementation details.
I don't want to move to another library and change whole websocket wrapper implementation, so I'll build library myself with few changes that allow pass custom user agent.

**Comment by Topinambur223606** [comment] 2021-02-14 14:07
Please evaluate the fix using the latest build and close the issue if bug is no longer reproducible.

**Comment by ntomilin** [comment] 2021-02-14 22:36
Checked. Works fine as supposed to.

**Comment by JusSumBum** [comment] 2021-02-14 22:36
> Please evaluate the fix using the latest build and close the issue if bug is no longer reproducible.

Looking great. Thx for continuing to support us.

**Closed** 2021-02-15 00:09 UTC
Labels: bug
